version: '3.8'

services:
  postgis:
    image: imresamu/postgis
    container_name: some-postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: secretuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: charging_app
    restart: unless-stopped
