spring:
  application:
    name: charging
  datasource:
    url: jdbc:postgresql://localhost:5432/charging_app
    username: secretuser
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

